version: "3"

services:
  db:
    build: ./db
    networks:
      - core
  clothing:
    build: ./clothing
    volumes:
      - ./clothing:/app
    depends_on:
      - db
    ports:
      - 5001:80
    networks:
      - core
  prices:
    build: ./prices
    volumes:
      - ./prices:/app
    ports:
      - 5002:80
    depends_on:
      - clothing
    networks:
      - core
      - front-end
  site:
    build: ./site
    volumes:
      - ./site:/src
    ports:
      - 5003:80
    depends_on:
      - prices
    networks:
      - front-end

networks:
  core:
    driver: bridge
  front-end:
    driver: bridge
