version: "3"

services:
  db:
    build: ./db
  clothing:
    build: ./clothing
    volumes:
      - ./clothing:/app
    depends_on:
      - db
    ports:
      - 5001:80
  prices:
    build: ./prices
    volumes:
      - ./prices:/app
    ports:
      - 5002:80
    depends_on:
      - clothing
  site:
    build: ./site
    volumes:
      - ./site:/src
    ports:
      - 5003:80
    depends_on:
      - prices
